### ISSUE TITLE
Project Development Setup

### ISSUE THREAD

**Issue by stas-at-ibm** [lukatarman/steam-game-stats#11]
## Description
Setup a Node.js development environment so that a developer can start implementing the features.

## Tasks
- [x] Pick a web server.
- [x] Pick http client: **axios**.
- [x] Pick database: **MongoDB**.
- [x] Pick testing library: **jasmine**.
- [x] Pick static code analysis packages: **eslint**, **prettier**.
- [x] Create a basic project directory structure.
