### ISSUE TITLE
Architecture Diagrams

### ISSUE THREAD

**Issue by stas-at-ibm** [lukatarman/steam-game-stats#12]
## Description
Create a high level and a medium level visual representation for components of the application.

## Tasks
- [x] Pick an architecture diagram style e.g. C4, UML, ...
- [x] Create a system context = high level.
- [x] Create a container diagram = medium level.
